title: jamogriff.dev
tagline: Developer + Guitarist + Handyman
description: >-
 Jamison Griffith is a full-stack developer, guitarist
 and handyman residing in Arvada Colorado. He has a background in
 biology and can churn out a lot of code using just a Terminal, git
 and Docker.
theme: jekyll-theme-gruv-poole

about:
  image:
    src: assets/images/profesh.png 
    alt: Picture of Jamison Griffith looking towards the sky
  socials:
    - { id: github, url: https://github.com/jamogriff }
    - { id: youtube, url: https://www.youtube.com/@jamisongriffith6308 }

# Add any pages that you want to be
# included in the masthead's navbar
masthead_pages:
  - songlist.html
  - about.html

# Replace with your own ID
# if you want Google Analytics
# google_analytics:UA-NNNNNNNN-N

# If you have an RSS
# feed plugin and want to
# advertise the feed, then
# set the feed file here
# rss_feed: atom.xml

# If you intend to use 
# an SEO plugin, then uncomment
# disable_simple_seo: true

plugins:
  - jekyll-cleansing-rite

collections:
  songs:
    sort_by: skill

### Developer-oriented config
permalink: pretty

# Optimize Jekyll
exclude:
  - .git
  - .rspec
  - .ruby-version
  - .gitignore
  - .travis.yml
  - rakefile.rb
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - README.md
  - spec/

liquid:
  error_mode: strict
  # Don't really recommend strict mode
  # until this is resolved: https://github.com/Shopify/liquid/issues/1034
  strict_variables: false
  strict_filters: true

sass:
  sass_dir: _sass
  sourcemap: development
  style: compressed
