title: Jamogriff
tagline: For that spark of imagination. 
description: >- # this means to ignore newlines until "baseurl:"
 My name is Jamison Griffith. I am a web developer, multi-instrumentalist
 and dog dad residing in Colorado. 
theme: jekyll-theme-gruv-poole

about:
  image:
    src: assets/banner-assets/logo-optimized.svg 
    alt: Image of Jamogriff
  socials:
    - { id: github, url: https://github.com/jamogriff }
    - { id: youtube, url: https://www.youtube.com/@jamisongriffith6308 }

# Add any pages that you want to be
# included in the masthead's navbar
masthead_pages:
  - about.html

# Replace with your own ID
# if you want Google Analytics
# google_analytics:UA-NNNNNNNN-N

# If you have an RSS
# feed plugin and want to
# advertise the feed, then
# set the feed file here
# rss_feed: atom.xml

# If you intend to use 
# an SEO plugin, then uncomment
# disable_simple_seo: true

### Developer-oriented config
permalink: pretty

# Optimize Jekyll
exclude:
  - .git
  - .rspec
  - .ruby-version
  - .gitignore
  - .travis.yml
  - CNAME
  - rakefile.rb
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - spec/
  - misc-assets/

liquid:
  error_mode: strict
  # Don't really recommend strict mode
  # until this is resolved: https://github.com/Shopify/liquid/issues/1034
  strict_variables: false
  strict_filters: true

sass:
  sass_dir: _sass
  sourcemap: development
  style: compressed
